### ISSUE TITLE
Inconsistent winding order on faces ?

### ISSUE THREAD

**Issue by mjzash** [gameprogcpp/code#12]
Enabling back face culling via `glEnable(GL_CULL_FACE)` makes some elements of the drawn objects appear / disappear.

e.g. enabling culling on chapter 12 shows the character but gui elements (quit menu) are hidden. Flipping the cull face via `glFrontFace(GL_CW)` flips this around where the gui elements are shown but the model is hidden.

**Comment by chalonverse** [comment]
This is most likely because the assets were not consistently authored, since I got the assets from different places.
