### ISSUE TITLE
Original sound files

### ISSUE THREAD

**Issue by BMarques** [gameprogcpp/code#20]
Hello,
I'm on chapter 7 and instead of using fmod, I want to use openal soft. Is it possible to share the original sound files instead of just the bank files?

Thanks.

**Comment by chalonverse** [comment]
The original asset files are included in the "Assets" subdirectories of the FMODStudio directories:
https://github.com/gameprogcpp/code/tree/master/FMODStudio/Chapter07/Assets
https://github.com/gameprogcpp/code/tree/master/FMODStudio/Chapter10/Assets
