### ISSUE TITLE
Chapter 2 - Pg 42 - Game::Shutdown() or Game::UnloadData()

### ISSUE THREAD

**Issue by KevinRunge** [gameprogcpp/code#28]
The book is a great learning experience, so please forgive any too detailed comments.

In chapter 2 page 42 the line
> However, this means that the code that loops over the `mActors` vector and deletes the actors (such as in `Game::Shutdown`) must be written carefully:

The actual loop which is given in the book is in the member function `Game::UnloadData()` (which is actually called from `Game::Shutdown`)

**Comment by chalonverse** [comment]
Good catch, I'll update the errata with this
