### ISSUE TITLE
Chapter 05 Runs Slow

### ISSUE THREAD

**Issue by Scr3amind** [gameprogcpp/code#31]
Hi mr Sanjay, first of all thank you for your books about game development. 
Is normal that the game example of the chapter 5 runs slow compared with the sdl version(no opengl)? 

on Asteroid.cpp i have this error:
`sc->SetTexture(game->GetTexture("Assets/Asteroid.png"));`

> Error E0167 argument of type "Texture *" is incompatible with parameter of type "Texture *"

Thank you in advance. Greetings from México.

**Comment by chalonverse** [comment]
Interesting, I noticed just now when I tested it on my PC, it is a bit choppy. That's weird because it wasn't like that before. It seems like the 3D games in the subsequent chapters run fine still, though. It could be a driver or something changed in OpenGL
