### ISSUE TITLE
Blender Exporter UV coordinates problem.

### ISSUE THREAD

**Issue by Scr3amind** [gameprogcpp/code#32]
Hi again Mr Sanjay
i have a problem with the blender exporter script.
i´m trying to replicate the cube found in assets with a simple texture.
(creating a cube in blender 2.79, unwrap and assign a texture)

![imagen](https://user-images.githubusercontent.com/23068771/66361457-7a468280-e944-11e9-9e6b-269b3b636595.png)

but when is loaded on the program of chapter 6 seems that the uv coordinates are wrong
![imagen](https://user-images.githubusercontent.com/23068771/66361669-37d17580-e945-11e9-94fd-dbcec9ebdeb1.png)

Comparing the two .gpmesh files (original cube vs my cube) found that the original cube have way more vertices. 28 vs 8. While mi cube have only one UVcoord per vertex , the original cube have diferent combinations of the same vertex with diferent UVcoords.
![imagen](https://user-images.githubusercontent.com/23068771/66361987-9814e700-e946-11e9-8843-1e7518d96bbc.png)

![imagen](https://user-images.githubusercontent.com/23068771/66361944-70258380-e946-11e9-9f4c-ae78c2275661.png)

Am i missing some step before exporting the mesh?

Thanks you so much for the book. Sorry for my bad english.
Greetings from México

**Comment by chalonverse** [comment]
Well, for a cube each side needs to have its own vertices. You can't share vertices between multiple sides because it won't work properly for lighting normals. So you can't just make your cube have 8 vertices for the corners. You need 4 vertices per side, 6 sides, so 24 vertices in total
