### ISSUE TITLE
Stuck on Exercise 2.3 

### ISSUE THREAD

**Issue by patoncrispy** [gameprogcpp/code#33]
Hey there. I'm stuck on Exercise 2.3 and not entirely sure of a few things.
- How do I figure out where the tiles should be rendered? I've assumed starting at { 0, 0 }, but not sure if that's correct. 

- How do I calculate the size of the tiles? I imported the CSV as a matrix and used the H and W of that as the H and W of each tile.

- What should the scene look like? I'm not entirely sure what I should be trying to achieve.

Also, I'm not entirely sure if I'm using `SDL_RenderCopyEx` correctly. I have:

```
SDL_RenderCopyEx(
					renderer,
					mTexture,
					&rect,
					nullptr,
					-Math::ToDegrees(mOwner->GetRotation()),
					nullptr,
					SDL_FLIP_NONE
				);
``` 

It's rendering stuff, but again, not entirely sure if I'm going in the right direction. 

Apologies if this isn't the right place to post these questions. I wasn't sure how else to get the answers! :)

**Comment by patoncrispy** [comment]
Nevermind! I got there in the end! 😄

**Comment by chalonverse** [comment]
Glad you figured it out!
