### ISSUE TITLE
Errata

### ISSUE THREAD

**Issue by LedLoaf** [gameprogcpp/code#46]
Is there an errata section for this book? I've seen different stuff from the source code, so I think it's messing me up at times.

**Comment by chalonverse** [comment]
There is an errata here: https://github.com/gameprogcpp/code/blob/master/Errata.md

But it may not have everything in it. If you notice something, let me know.

**Comment by LedLoaf** [comment]
> There is an errata here: https://github.com/gameprogcpp/code/blob/master/Errata.md
> 
> But it may not have everything in it. If you notice something, let me know.

Sure thing, I appreciate the help. Would you want me to submit it over there?

**Comment by chalonverse** [comment]
The easiest is you can submit a pull request for the additions, otherwise you could just reply to this thread with any notes
