### ISSUE TITLE
Chapter 10 page 327 : Missing code!

### ISSUE THREAD

**Issue by tehredplague** [gameprogcpp/code#51]
Source code is correct on this but just throwing it out there that PhysWorld::SegmentCast implementation in the book is missing
"closestT = t;" in the example code after "if (t < closestT)" on page 327.

Didn't know if this was appropriate errata, but I'm sure you'd like to be aware of typos! Fantastic book by the way.

**Comment by chalonverse** [comment]
Yes you are correct, it's missing there. I fixed the code in the repo in #40 but forgot to update the errata. I updated it just now.
